[build-system]
requires = ["setuptools", "pip >= 10"]
build-backend = "setuptools.build_meta"

[project]
name = "pysatCDAAC"
version = "0.0.4"
description = "pysat support for CDAAC Instruments"
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}
authors = [
    {name = "Jeff Klenzing, et al.", email = "pysat.developers@gmail.com"},
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Topic :: Scientific/Engineering :: Astronomy",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows"
]
keywords = [
  "pysat",
  "ionosphere",
  "cosmic",
  "radio occultation"
]
dependencies = [
  "netCDF4",
  "numpy",
  "pandas",
  "pysat >= 3.0.4",
  "requests",
  "xarray"
]

[project.optional-dependencies]
test = [
  "coveralls < 3.3",
  "flake8",
  "flake8-docstrings",
  "hacking >= 1.0",
  "pytest",
  "pytest-cov",
  "pytest-ordering"
]
doc = [
  "extras_require",
  "ipython",
  "m2r2",
  "numpydoc",
  "sphinx < 7.0",
  "sphinx-autoapi",
  "sphinx_rtd_theme >= 1.2.2"
]

[project.urls]
Documentation = "https://pysatcdaac.readthedocs.io/en/latest/"
Source = "https://github.com/pysat/pysatCDAAC"

[tool.coverage.report]

[tool.pytest.ini_options]
addopts = "--cov=pysatCDAAC"
markers = [
  "all_inst",
  "download",
  "no_download",
  "load_options",
  "first",
  "second"
]
